# external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-my-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: eso-my-secret
    creationPolicy: Owner
  data:
    - secretKey: MY_SECRET
      remoteRef:
        key: secret/myapp
        property: SECRET_VALUE
